# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63597e0727f5d14656662ac5a7944fe5"
application_url = "https://norway-slides-lately-veterinary.trycloudflare.com"
embedded = true
name = "remix_app"
handle = "remix_app-5"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://norway-slides-lately-veterinary.trycloudflare.com/auth/callback",
  "https://norway-slides-lately-veterinary.trycloudflare.com/auth/shopify/callback",
  "https://norway-slides-lately-veterinary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
